### ISSUE TITLE
操作系统实验5-新建磁盘并格式化后会出现段错误

### ISSUE THREAD

**Issue by YZZZZZ2333** [dorapocket/CScode#1]
原因是scanf和fgets一起用会出现奇奇怪怪的错误，我将function.c文件中`scanf("%d",&size);`改成了用fgets读入然后转成数字的方式，可以解决问题
//判断是否格式化  
    if(strcmp(block0.identify,"MYDISK")!=0){  
	    int size;
        printf("磁盘尚未格式化，开始格式化\n");
	    printf("请输入扇区大小：\n");
	    //scanf("%d",&size);
        char tmp[20];
        fgets(tmp,10,stdin);
        //printf("#%s",tmp);
        size=atoi(tmp);
        printf("已将扇区大小设定为：%d\n",size);
	    block0.blocksize=size;
	    BLOCK_SIZE=size;
        format();
    }
![image](https://user-images.githubusercontent.com/25920981/103339559-9e97fd00-4abc-11eb-9b12-b539d27a0a3d.png)

**Comment by dorapocket** [comment]
好的哈，谢谢！测试完后你可以提pr
